export default {
    "data" : {
       "id" : "3817",
       "type" : "referral",
       "attributes":{
          "name":"Loyalty Rewards Program ddd",
          "description":"",
          "id_site":"4293",
          "start_date":"1599636660",
          "end_date":"1599636660",
          "image_url":"upload/img/817/17/3817_contest_1600476767.png",
          "promo_url":"https://bit.ly/2ZmKvrp",
          "bg_color":"#333333",
          "status":"1",
          "published":"1",
          "currency":"AUD",
          "is_guest_order":1,
          "currency_symbol":"$",
          "login_url":"https://maverickmav.org/wpwoothree/index.php/my-account-2/",
          "register_url":"https://maverickmav.org/wpwoothree/index.php/my-account-2/",
          "terms_url":"https://maverickmav.org/wpwoothree/index.php/my-account-2/",
          "shopping_url":"",
          "terms_condition":[
             
          ],
          "privacy_policy":[
             
          ],
          "points_settings":{
             "is_bonus_points":1,
             "points_value":"fixed",
             "price":"1",
             "points":"1",
             "minimum_order":0,
             "points_type":"SUBTOTAL",
             "roundoff_type":"ROUND",
             "is_welcome_bonus":1,
             "welcome_bonus":"111",
             "welcome_bonus_title":"Welcome to Happy Perks, a rewards program! Its FREE to join & filled with Perks!",
             "is_pay_by_points":1,
             "point_per_dollar":0
          }
       },
       "relationships":{
          "referral":{
             "data":{
                "id":"3817",
                "type":"referral",
                "attributes":{
                   "is_purchase_required":0,
                   "enable_guest_order":1,
                   "goal":"1",
                   "maximum_rewards":0,
                   "reward_type":"unique",
                   "referrer_reward_types":"points",
                   "referral_fresh_install":0,
                   "referral_description":"Invite your friends and get rewards when they make a purchase.",
                   "referrer_reward_points":"200",
                   "referrer_onesided":"",
                   "is_new":1,
                   "coupon_on_friend":1,
                   "coupon_description":"Share this url to give your friends an awesome offer! You’ll earn rewards when they make a purchase.",
                   "common_referrer_reward":"",
                   "is_referral_completed":1,
                   "realtime_coupon_type_friend":"1",
                   "realtime_minimum_order_friend":0,
                   "realtime_coupon_type":1,
                   "realtime_coupon_value":"10",
                   "realtime_minimum_order":0,
                   "is_reward_points_percentage":0,
                   "reward_points_percentage":"10",
                   "status":1
                }
             }
          },
          "entries":{
             "data":[
                {
                   "id":"13597",
                   "type":"quiz_choice",
                   "attributes":{
                      "title":"Quiz",
                      "entries":"1",
                      "is_mandatory":0,
                      "is_daily_entry":0,
                      "is_notify":0,
                      "form_fields":"",
                      "status":"1",
                      "settings":{
                         "question":"Select A",
                         "info":"",
                         "answers":[
                            {
                               "answer":"A",
                               "is_right":"1"
                            },
                            {
                               "answer":"B",
                               "is_right":"0"
                            },
                            {
                               "answer":"C",
                               "is_right":"0"
                            }
                         ],
                         "msg_success":"Correct",
                         "msg_error":"Wring",
                         "quiz_img":"",
                         "is_min_one_ans":"0",
                         "mode_points":"1",
                         "mode_instant":"1",
                         "instant_reward":"",
                         "instant_reward_opt":"1",
                         "instant_reward_text":"",
                         "instant_reward_cpn":"",
                         "instant_reward_lnk":"",
                         "reward_type":"1",
                         "realtime_coupon_type":"1",
                         "realtime_coupon_value":"10",
                         "realtime_min_order":0,
                         "currency":"$",
                         "worth_entries":"1",
                         "mode_query":0
                      }
                   }
                },
                {
                   "id":"13596",
                   "type":"visit_page",
                   "attributes":{
                      "title":"Visit a Page",
                      "entries":"10",
                      "is_mandatory":0,
                      "is_daily_entry":0,
                      "is_notify":0,
                      "form_fields":"",
                      "status":"1",
                      "settings":{
                         "page_links":"https://appsmav.com/gratisfaction.php",
                         "mode_points":"1",
                         "mode_instant":"1",
                         "instant_reward":"",
                         "instant_reward_opt":"1",
                         "instant_reward_text":"",
                         "instant_reward_cpn":"",
                         "instant_reward_lnk":"",
                         "reward_type":"1",
                         "realtime_coupon_type":"1",
                         "realtime_coupon_value":"10",
                         "realtime_min_order":0,
                         "currency":"$",
                         "worth_entries":"10",
                         "mode_query":0
                      }
                   }
                },
                {
                   "id":"13580",
                   "type":"facebook_share",
                   "attributes":{
                      "title":"Share on Facebook",
                      "entries":"50",
                      "is_mandatory":1,
                      "is_daily_entry":1,
                      "is_notify":1,
                      "form_fields":"",
                      "status":"1",
                      "settings":{
                         "share_img":"",
                         "last_update":1599640432,
                         "share_title":"Check out this website. They are amazing!",
                         "share_caption":"My WordPress Website",
                         "share_desc":"You have to check out this website. They have amazing products & service!",
                         "landing_url":"https://maverickmav.org/wpwoothree",
                         "mode_points":"1",
                         "mode_instant":"0",
                         "instant_reward":"",
                         "instant_reward_opt":0,
                         "instant_reward_text":"",
                         "instant_reward_cpn":"",
                         "instant_reward_lnk":"",
                         "reward_type":0,
                         "realtime_coupon_type":1,
                         "realtime_coupon_value":10,
                         "realtime_min_order":0,
                         "currency":"$",
                         "worth_entries":"50",
                         "mode_query":0
                      }
                   }
                },
                {
                   "id":"13582",
                   "type":"newsletter_subscription",
                   "attributes":{
                      "title":"Subscribe to our mailing list",
                      "entries":"50",
                      "is_mandatory":0,
                      "is_daily_entry":0,
                      "is_notify":0,
                      "form_fields":"",
                      "status":"1",
                      "settings":{
                         "title":"Subscribe to our mailing list",
                         "esp_id":"",
                         "esp_list_id":"",
                         "esp_list_name":"",
                         "subscription_note":"",
                         "platform_marketing_permission":"0",
                         "enable_double_optin":"0",
                         "show_gdpr_msg":"0",
                         "mode_points":"1",
                         "mode_instant":"0",
                         "instant_reward":"",
                         "instant_reward_opt":"1",
                         "instant_reward_text":"",
                         "instant_reward_cpn":"",
                         "instant_reward_lnk":"",
                         "reward_type":"1",
                         "realtime_coupon_type":"1",
                         "realtime_coupon_value":"10",
                         "realtime_min_order":0,
                         "currency":"$",
                         "worth_entries":"50",
                         "mode_query":0
                      }
                   }
                },
                {
                   "id":"13581",
                   "type":"twitter_tweet",
                   "attributes":{
                      "title":"Share on Twitter",
                      "entries":"50",
                      "is_mandatory":1,
                      "is_daily_entry":1,
                      "is_notify":1,
                      "form_fields":"",
                      "status":"1",
                      "settings":{
                         "tweet":"Check out this website. They have amazing products & service!",
                         "tweet_url":"https://maverickmav.org/wpwoothree",
                         "mode_points":"1",
                         "mode_instant":"0",
                         "instant_reward":"",
                         "instant_reward_opt":0,
                         "instant_reward_text":"",
                         "instant_reward_cpn":"",
                         "instant_reward_lnk":"",
                         "reward_type":0,
                         "realtime_coupon_type":1,
                         "realtime_coupon_value":10,
                         "realtime_min_order":0,
                         "currency":"$",
                         "worth_entries":"50",
                         "mode_query":0
                      }
                   }
                }
             ]
          }
       },
       "includes":{
          "shop":{
             "data":{
                "id":"4293",
                "type":"shop",
                "attributes":{
                   "name":"My WordPress Website",
                   "site_name":"My WordPress Website",
                   "plugin_type":"WP",
                   "url":"https://maverickmav.org/wpwoothree",
                   "logo":"",
                   "email":"mukeshchannelabc@gmail.com",
                   "timezone":"America/Chicago",
                   "max_users":"10",
                   "language":"en_US",
                   "exclusion_period":"",
                   "date_format":"d/m/Y",
                   "email_reply_to":"mukeshchannelabc@gmail.com",
                   "status":"1",
                   "date_created":"1599636680",
                   "date_updated":"1600341738"
                }
             }
          },
          "rewards":{
             "data":[
                {
                   "id":"4899",
                   "type":"rewards",
                   "attributes":{
                      "name":"$5 off coupon",
                      "type":"",
                      "description":"Redeem $5 off coupon for 500 points",
                      "points":"10",
                      "quantity":0,
                      "image_url":"assets/img/reward.jpg",
                      "is_type_other":0,
                      "is_coupon":"1",
                      "in_stock":"1",
                      "order_by":0,
                      "realtime_coupon_on":"1",
                      "status":"1",
                      "coupon_type":"2",
                      "coupon_value":"5",
                      "minimum_order":0
                   }
                },
                {
                   "id":"4900",
                   "type":"rewards",
                   "attributes":{
                      "name":"$10 off coupon",
                      "type":"",
                      "description":"Redeem $10 off coupon for 1000 points",
                      "points":"20",
                      "quantity":0,
                      "image_url":"assets/img/reward.jpg",
                      "is_type_other":0,
                      "is_coupon":"1",
                      "in_stock":"1",
                      "order_by":0,
                      "realtime_coupon_on":"1",
                      "status":"1",
                      "coupon_type":"2",
                      "coupon_value":"10",
                      "minimum_order":0
                   }
                },
                {
                   "id":"4901",
                   "type":"rewards",
                   "attributes":{
                      "name":"$15 off coupon",
                      "type":"",
                      "description":"Redeem $15 off coupon for 1500 points",
                      "points":"30",
                      "quantity":0,
                      "image_url":"assets/img/reward.jpg",
                      "is_type_other":0,
                      "is_coupon":"1",
                      "in_stock":"1",
                      "order_by":0,
                      "realtime_coupon_on":"1",
                      "status":"1",
                      "coupon_type":"2",
                      "coupon_value":"15",
                      "minimum_order":0
                   }
                },
                {
                   "id":"4902",
                   "type":"rewards",
                   "attributes":{
                      "name":"$20 off coupon",
                      "type":"",
                      "description":"Redeem $20 off coupon for 2000 points",
                      "points":"40",
                      "quantity":0,
                      "image_url":"assets/img/reward.jpg",
                      "is_type_other":0,
                      "is_coupon":"1",
                      "in_stock":"1",
                      "order_by":0,
                      "realtime_coupon_on":"1",
                      "status":"1",
                      "coupon_type":"2",
                      "coupon_value":"20",
                      "minimum_order":0
                   }
                }
             ]
          },
          "events":{
             "data":[
                {
                   "id":"856",
                   "type":"events",
                   "attributes":{
                      "name":"Enter your birthday",
                      "type":"member_birthday",
                      "other_type":"",
                      "description":"Enter your birthday Desription",
                      "reward_description":"Advanced Happy Birthday",
                      "is_year_required":"1",
                      "is_points":"1",
                      "points":"100",
                      "has_coupon":"1",
                      "minimum_purchase":"20.000",
                      "purchase_days":"10",
                      "instruction":"Instruction for redeeming this coupon",
                      "status":"1"
                   }
                },
                {
                   "id":"863",
                   "type":"events",
                   "attributes":{
                      "name":"Reminder Name",
                      "type":"member_anniversary",
                      "other_type":"",
                      "description":"",
                      "reward_description":"Reminder Wish Description",
                      "is_year_required":0,
                      "is_points":"1",
                      "points":"100",
                      "has_coupon":0,
                      "minimum_purchase":0,
                      "purchase_days":0,
                      "instruction":"",
                      "status":"1"
                   }
                }
             ]
          }
       }
    }
 }